In [1]:
import pandas as pd

In [2]:
pd.__version__

'2.3.1'

In [4]:
df = pd.read_csv('car_fuel_efficiency.csv')

In [5]:
df.head()

,engine_displacement,num_cylinders,horsepower,vehicle_weight,acceleration,model_year,origin,fuel_type,drivetrain,num_doors,fuel_efficiency_mpg
0,170,3.0,159.0,3413.433759,17.7,2003,Europe,Gasoline,All-wheel drive,0.0,13.231729
1,130,5.0,97.0,3149.664934,17.8,2007,USA,Gasoline,Front-wheel drive,0.0,13.688217
2,170,NaN,78.0,3079.038997,15.1,2018,Europe,Gasoline,Front-wheel drive,0.0,14.246341
3,220,4.0,NaN,2542.392402,20.2,2009,USA,Diesel,All-wheel drive,2.0,16.912736
4,210,1.0,140.0,3460.870990,14.4,2009,Europe,Gasoline,All-wheel drive,2.0,12.488369

In [6]:
df.fuel_type.nunique()

2

In [9]:
has_null = df.isnull().sum().apply(lambda x: 1 if x > 0 else 0)
has_null.sum()

np.int64(4)

In [14]:
df[df['origin']=='Asia']['fuel_efficiency_mpg'].max()

np.float64(23.759122836520497)

In [15]:
df.horsepower.median()

np.float64(149.0)

In [18]:
hp_mode = df.horsepower.mode()
hp_mode

0    152.0
Name: horsepower, dtype: float64

In [19]:
df.horsepower.fillna(hp_mode).median()

np.float64(149.0)

In [37]:
df_X = df[df.origin == 'Asia'][['vehicle_weight','model_year']].head(7)
df_X

    vehicle_weight  model_year
8      2714.219310        2016
12     2783.868974        2010
14     3582.687368        2007
20     2231.808142        2011
21     2659.431451        2016
34     2844.227534        2014
38     3761.994038        2019

In [38]:
import numpy as np

X = df_X.to_numpy()

In [39]:
XTX = X.T.dot(X)

In [40]:
y = np.array([1100, 1300, 800, 900, 1000, 1100, 1200])

In [41]:
w = np.linalg.inv(XTX).dot(X.T).dot(y)
w

array([0.01386421, 0.5049067 ])

In [42]:
w.sum()

np.float64(0.5187709081074016)